import { useState, useEffect } from 'react'
import api from '../../utils/api'
import toast from 'react-hot-toast'
import { 
  Settings as SettingsIcon, CloudDownload, Mail, Globe, 
  CheckCircle, XCircle, RefreshCw, Save, ShieldAlert, FileJson
} from 'lucide-react'

export default function GoogleFormSettings() {
  const [form, setForm] = useState({
    googleSpreadsheetId: '',
    googleServiceAccountJson: '',
    gmailUser: '',
    gmailAppPassword: '',
    examPortalUrl: 'http://localhost:5173'
  })
  
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [testing, setTesting] = useState(false)
  
  const [testResult, setTestResult] = useState(null)

  useEffect(() => {
    const fetchSettings = async () => {
      try {
        const res = await api.get('/admin/settings')
        if (res.data.settings) {
          setForm({
            googleSpreadsheetId: res.data.settings.googleSpreadsheetId || '',
            googleServiceAccountJson: res.data.settings.googleServiceAccountJson || '',
            gmailUser: res.data.settings.gmailUser || '',
            gmailAppPassword: res.data.settings.gmailAppPassword || '',
            examPortalUrl: res.data.settings.examPortalUrl || 'http://localhost:5173'
          })
        }
      } catch (err) {
        toast.error('Failed to load system configuration')
      } finally {
        setLoading(false)
      }
    }
    fetchSettings()
  }, [])

  const handleSave = async (e) => {
    e.preventDefault()
    setSaving(true)
    try {
      await api.post('/admin/settings', form)
      toast.success('Configuration saved successfully!')
    } catch (err) {
      toast.error(err.response?.data?.message || 'Save failed')
    } finally {
      setSaving(false)
    }
  }

  const handleTestConnection = async () => {
    setTesting(true)
    setTestResult(null)
    try {
      const res = await api.post('/admin/settings/test', form)
      setTestResult(res.data)
      if (res.data.sheets?.success && res.data.smtp?.success) {
        toast.success('All connections established successfully!')
      } else {
        toast.error('Some connections failed verification.')
      }
    } catch (err) {
      toast.error('Testing connection failed.')
    } finally {
      setTesting(false)
    }
  }

  if (loading) return (
    <div className="flex items-center justify-center h-64">
      <div className="text-center">
        <div className="spinner mx-auto mb-3" />
        <p className="text-slate-400">Loading configurations...</p>
      </div>
    </div>
  )

  return (
    <div className="max-w-4xl space-y-6 fade-in">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold gradient-text flex items-center gap-2">
          <SettingsIcon size={24} className="text-blue-500" /> System Settings
        </h1>
        <p className="text-slate-400 text-sm mt-1">
          Configure Google Sheets API synchronization and Gmail SMTP credentials
        </p>
      </div>

      {/* Google Form Field Reference */}
      <div className="glass-card p-5 border border-blue-500/20 bg-blue-500/5">
        <h3 className="text-sm font-semibold text-blue-300 mb-3 flex items-center gap-2">
          <CloudDownload size={15} /> Expected Google Form: <span className="font-mono text-xs text-blue-400">SBIST Online Examination Registration</span>
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {[
            { col: 'B', label: 'Student Name', type: 'Short Answer' },
            { col: 'C', label: 'Email Address', type: 'Email' },
            { col: 'D', label: 'Roll Number', type: 'Short Answer' },
            { col: 'E', label: 'Phone Number', type: 'Short Answer' },
            { col: 'F', label: 'Department', type: 'Dropdown (CSE / ECE …)' },
            { col: 'G', label: 'Year', type: 'Dropdown (1–4)' },
            { col: 'H', label: 'Semester', type: 'Dropdown (1 / 2)' },
            { col: 'I', label: 'Section', type: 'Dropdown (A / B / C)' },
            { col: 'J', label: 'Academic Year', type: 'Short Answer (e.g. 2025-26)' },
            { col: 'K', label: 'Sync Status', type: 'Written by app — do not edit' },
          ].map(({ col, label, type }) => (
            <div key={col} className="flex items-start gap-2 text-xs">
              <span className="font-mono text-slate-500 w-4 shrink-0">Col {col}</span>
              <div>
                <span className="text-slate-200 font-medium">{label}</span>
                <span className="text-slate-500 ml-1">— {type}</span>
              </div>
            </div>
          ))}
        </div>
        <p className="text-[11px] text-slate-500 mt-3">
          Column A is Timestamp (auto-generated by Google Forms). The sync job reads every 5 minutes and writes <code className="text-blue-400">Synced</code> to column K when processed.
        </p>
      </div>

      <form onSubmit={handleSave} className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Left panel: Google Sheet Sync Settings */}
          <div className="glass-card p-6 space-y-4">
            <h3 className="text-base font-semibold text-slate-200 flex items-center gap-2 border-b border-slate-700/50 pb-2">
              <CloudDownload size={18} className="text-blue-400" /> Google Sheet Sync
            </h3>

            <div className="space-y-3">
              <div>
                <label className="input-label">Google Spreadsheet ID</label>
                <input
                  type="text"
                  className="input-field"
                  placeholder="e.g. 1a2b3c4d5e6f7g8h9i..."
                  value={form.googleSpreadsheetId}
                  onChange={e => setForm(p => ({ ...p, googleSpreadsheetId: e.target.value }))}
                />
                <p className="text-[11px] text-slate-500 mt-1">
                  The ID of the spreadsheet linked to your Google Form.
                </p>
              </div>

              <div>
                <label className="input-label flex items-center gap-1">
                  <FileJson size={13} className="text-slate-400" /> Service Account JSON Credentials
                </label>
                <textarea
                  className="input-field font-mono text-xs h-36"
                  placeholder='Pasted content of credentials.json...'
                  value={form.googleServiceAccountJson}
                  onChange={e => setForm(p => ({ ...p, googleServiceAccountJson: e.target.value }))}
                />
                <p className="text-[11px] text-slate-500 mt-1">
                  Paste the content of your Google Cloud Service Account private key JSON.
                </p>
              </div>
            </div>
          </div>

          {/* Right panel: Gmail SMTP Settings */}
          <div className="glass-card p-6 space-y-4">
            <h3 className="text-base font-semibold text-slate-200 flex items-center gap-2 border-b border-slate-700/50 pb-2">
              <Mail size={18} className="text-indigo-400" /> Gmail SMTP (App Password)
            </h3>

            <div className="space-y-4">
              <div>
                <label className="input-label">SMTP Username (Gmail Address)</label>
                <input
                  type="email"
                  className="input-field"
                  placeholder="e.g. notifications@sbist.edu"
                  value={form.gmailUser}
                  onChange={e => setForm(p => ({ ...p, gmailUser: e.target.value }))}
                />
              </div>

              <div>
                <label className="input-label">Gmail App Password (16 Characters)</label>
                <input
                  type="password"
                  className="input-field"
                  placeholder="e.g. abcd efgh ijkl mnop"
                  value={form.gmailAppPassword}
                  onChange={e => setForm(p => ({ ...p, gmailAppPassword: e.target.value }))}
                />
                <p className="text-[11px] text-slate-500 mt-1">
                  Generate a 16-character App Password under your Google Account Security settings.
                </p>
              </div>

              <div>
                <label className="input-label flex items-center gap-1">
                  <Globe size={13} className="text-slate-400" /> Exam Portal Base URL
                </label>
                <input
                  type="url"
                  className="input-field"
                  placeholder="http://localhost:5173"
                  value={form.examPortalUrl}
                  onChange={e => setForm(p => ({ ...p, examPortalUrl: e.target.value }))}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Connection Test Results */}
        {testResult && (
          <div className="glass-card p-5 border border-slate-700/60 grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Sheets connection status */}
            <div className="flex items-start gap-3">
              {testResult.sheets?.success ? (
                <CheckCircle className="text-emerald-400 mt-0.5" size={20} />
              ) : (
                <XCircle className="text-red-400 mt-0.5" size={20} />
              )}
              <div>
                <h4 className="text-sm font-semibold text-slate-200">Google Sheets Connection</h4>
                {testResult.sheets?.success ? (
                  <p className="text-xs text-slate-400 mt-0.5">
                    Connected! Spreadsheet: <strong>{testResult.sheets.title}</strong>
                  </p>
                ) : (
                  <p className="text-xs text-red-400 mt-0.5 leading-relaxed">
                    Failed: {testResult.sheets.reason}
                  </p>
                )}
              </div>
            </div>

            {/* SMTP connection status */}
            <div className="flex items-start gap-3">
              {testResult.smtp?.success ? (
                <CheckCircle className="text-emerald-400 mt-0.5" size={20} />
              ) : (
                <XCircle className="text-red-400 mt-0.5" size={20} />
              )}
              <div>
                <h4 className="text-sm font-semibold text-slate-200">Gmail SMTP Service</h4>
                {testResult.smtp?.success ? (
                  <p className="text-xs text-slate-400 mt-0.5">SMTP transport verified successfully.</p>
                ) : (
                  <p className="text-xs text-red-400 mt-0.5 leading-relaxed">
                    Failed: {testResult.smtp.reason}
                  </p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Form Actions */}
        <div className="flex justify-end gap-3">
          <button
            type="button"
            onClick={handleTestConnection}
            disabled={testing || saving}
            className="btn-secondary flex items-center gap-2"
          >
            {testing ? <RefreshCw className="animate-spin" size={16} /> : <ShieldAlert size={16} />}
            Test Connections
          </button>

          <button
            type="submit"
            disabled={saving || testing}
            className="btn-primary flex items-center gap-2 px-6"
          >
            {saving ? <div className="spinner !w-4 !h-4 !border-t-white" /> : <Save size={16} />}
            Save Settings
          </button>
        </div>
      </form>
    </div>
  )
}
